<a href="https://colab.research.google.com/github/sagorbrur/my_colab_notebook/blob/master/Pytorch_tutorial_model_basic1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import torch, torchvision
torch.__version__

'1.3.1'

In [0]:
import torch.nn as nn


In [0]:
# creating linear regression model
class linear(nn.Module):
  def __init__(self):
    super(linear, self).__init__()
    self.dense = nn.Linear(5, 1)

  def forward(self, x):
    x = self.dense(x)
    return x

  

In [5]:
model = linear()
model

linear(
  (dense): Linear(in_features=5, out_features=1, bias=True)
)

In [6]:
for p in model.parameters():
  print(p)

Parameter containing:
tensor([[ 0.0066,  0.4038,  0.0641, -0.0900,  0.1780]], requires_grad=True)
Parameter containing:
tensor([0.1042], requires_grad=True)


In [7]:
nn.ParameterList(model.parameters())

ParameterList(
    (0): Parameter containing: [torch.FloatTensor of size 1x5]
    (1): Parameter containing: [torch.FloatTensor of size 1]
)

In [8]:
model.state_dict()


OrderedDict([('dense.weight',
              tensor([[ 0.0066,  0.4038,  0.0641, -0.0900,  0.1780]])),
             ('dense.bias', tensor([0.1042]))])

In [9]:
x = torch.randn(5, dtype = torch.float)   # generate a single data instance
print(x)
print(model(x)) 

tensor([ 2.4799,  1.4912, -1.0688, -0.5471,  0.2823])
tensor([0.7538], grad_fn=<AddBackward0>)


In [10]:
x = torch.randn(3, 5, dtype = torch.float)    # generate 3 random data instance
print(x)
print(model(x))

tensor([[-1.4807, -0.4611,  0.7988, -1.9477,  0.0901],
        [-1.0158,  1.6428, -1.5025,  0.3722, -0.5055],
        [-0.0817, -2.2221, -0.5454, -0.1207, -0.2876]])
tensor([[ 0.1508],
        [ 0.5410],
        [-0.8690]], grad_fn=<AddmmBackward>)
