<a href="https://colab.research.google.com/github/sagorbrur/my_colab_notebook/blob/master/XOR_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim

In [0]:
epoch = 50000

In [0]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(2, 3, True)
    self.fc2 = nn.Linear(3, 1, True)

  def forward(self, x):
    x = F.sigmoid(self.fc1(x))
    x = self.fc2(x)
    return x





In [10]:
net = Net()
inputs = list(map(lambda s: Variable(torch.Tensor([s])), [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]))


inputs

[tensor([[0., 0.]]),
 tensor([[0., 1.]]),
 tensor([[1., 0.]]),
 tensor([[1., 1.]])]

In [12]:
targets = list(map(lambda s: Variable(torch.Tensor([s])), [
    [0],
    [1],
    [1],
    [0]
]))

targets

[tensor([[0.]]), tensor([[1.]]), tensor([[1.]]), tensor([[0.]])]

In [0]:
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.01)


In [19]:
print("Training loop:")

for idx in range(0, epoch):
  for input, target in zip(inputs, targets):
    optimizer.zero_grad()
    output = net(input)
    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
  if idx % 5000 == 0:
      print("Epoch {: >8} Loss: {}".format(idx, loss.data.numpy()))



Training loop:
Epoch        0 Loss: 0.0459454320371151


/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1386: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


Epoch     5000 Loss: 0.2801951766014099
Epoch    10000 Loss: 0.0036854594945907593
Epoch    15000 Loss: 1.0168754727146734e-09
Epoch    20000 Loss: 1.0168754727146734e-09
Epoch    25000 Loss: 1.0168754727146734e-09
Epoch    30000 Loss: 1.0168754727146734e-09
Epoch    35000 Loss: 1.0168754727146734e-09
Epoch    40000 Loss: 1.0168754727146734e-09
Epoch    45000 Loss: 1.0168754727146734e-09


In [20]:
print("")
print("Final Result")
for input, target in zip(inputs, targets):
  output = net(input)
  print("Input:[{},{}] Target:[{}] Predicted:[{}] Error:[{}]".format(
        int(input.data.numpy()[0][0]),
        int(input.data.numpy()[0][1]),
        int(target.data.numpy()[0]),
        round(float(output.data.numpy()[0]), 4),
        round(float(abs(target.data.numpy()[0] - output.data.numpy()[0])), 4)
    ))


Final Result
Input:[0,0] Target:[0] Predicted:[0.0] Error:[0.0]
Input:[0,1] Target:[1] Predicted:[1.0] Error:[0.0]
Input:[1,0] Target:[1] Predicted:[1.0] Error:[0.0]
Input:[1,1] Target:[0] Predicted:[0.0] Error:[0.0]


/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1386: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
